# 文件上传配置!
spring:
  servlet:
    multipart:
      max-request-size: 5GB
      max-file-size: 1GB



# windows(开发时!) 下的路劲!
# 发布记得要改称linux 下的路径!
upload: D:\Users\zdz\IdeaProjects\upload_demo\upload\




# 数据库配置,不用拷贝!
spring.datasource:
  url: jdbc:mysql://127.0.0.1:3306/exam_online?charactionEncoding=utf8&useSSL=true
  username: root
  password: root
  driver-class-name: com.mysql.cj.jdbc.Driver
